# Generated by Django 3.2.5 on 2021-09-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Craft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('content', models.TextField(max_length=2500)),
                ('image', models.FileField(upload_to='upload/')),
                ('published', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=1000)),
            ],
        ),
    ]
