# Generated by Django 3.2.5 on 2021-09-14 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crafts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='craft',
            name='url',
        ),
    ]
