# Generated by Django 3.2.7 on 2021-09-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafts', '0002_remove_craft_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='craft',
            options={'verbose_name': 'Поделки'},
        ),
        migrations.AlterField(
            model_name='craft',
            name='content',
            field=models.TextField(max_length=2500, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='craft',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Заголовок'),
        ),
    ]
