# Generated by Django 3.2.7 on 2021-09-17 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crafts', '0003_auto_20210917_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='craft',
            options={'verbose_name': 'Поделка', 'verbose_name_plural': 'Поделки'},
        ),
    ]
