# Generated by Django 3.2.5 on 2021-09-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Заголовок')),
                ('content', models.TextField(max_length=2500, verbose_name='Содержание')),
                ('image', models.FileField(upload_to='upload/')),
                ('published', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Новость о рыбалке',
                'verbose_name_plural': 'Новости о рыбалке',
            },
        ),
    ]
