# Generated by Django 3.2.7 on 2021-09-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telesettings',
            name='tg_message',
            field=models.TextField(max_length=2000, verbose_name='Текст сообщения'),
        ),
    ]
