# Generated by Django 3.2.7 on 2021-09-17 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleId',
        ),
    ]
