# Generated by Django 3.2.7 on 2021-09-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterField(
            model_name='article',
            name='address',
            field=models.CharField(max_length=300, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(max_length=2500, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='article',
            name='place',
            field=models.CharField(max_length=100, unique=True, verbose_name='Место'),
        ),
    ]
