# Generated by Django 3.2.7 on 2021-09-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnir', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turnir',
            options={'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AlterField(
            model_name='turnir',
            name='content',
            field=models.TextField(max_length=3000, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='turnir',
            name='date',
            field=models.CharField(max_length=100, verbose_name='Дата события'),
        ),
        migrations.AlterField(
            model_name='turnir',
            name='phone',
            field=models.IntegerField(verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='turnir',
            name='place',
            field=models.CharField(max_length=300, verbose_name='Место проведения'),
        ),
        migrations.AlterField(
            model_name='turnir',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Заголовок'),
        ),
    ]
